package com.disney.omnicart.model

import java.sql.Timestamp

import scala.collection.mutable

case class OmnicartHbase(
                          var areaStartDateList: List[Timestamp],
                          var areaStartDateDistinctCount: Int,
                          var areaStartDateMonth: Int,
                          var areaStartDateMonthList: List[Int],
                          var daysTripDuration: Long,
                          var daysTripDurationList: List[Long],
                          var daysTripDurationDistinctCount: Int,
                          var daysTripDurationMedian: Long,

                          var eventNum: Int,
                          var swid: String,
                          var swidList: List[String],
                          var cartStatus: String,
                          var cartStatusList: List[String],
                          var cartSwidExists: Boolean,
                          var cartTotalAmountList: List[Double],
                          var cartTotalAmountMean: Double,
                          var cartTotalAmountMedian: Double,
                          var cartTotalAmountDistinctCount: Int,
                          var cartCookieId: String,
                          var cartCookieIdExistsList: List[Boolean],
                          var cartCookieIdDistinctCount:Int,
                          var cartCookieIdExists: Boolean,

                          var cartSecondaryGuests: Boolean,
                          var cartSecondaryGuestsList: List[Boolean],
                          var cartSecondaryGuestsDistinctCount: Int,

                          var cartStartDate: Timestamp,
                          var cartStartDateList: List[Timestamp],
                          var daysCreatedAheadOfTripList: List[Long],
                          var daysCreatedAheadOfTripMedian: Long,
                          var daysCreatedAheadOfTripDistinctCount: Int,
                          var createDatetimeMonth: Int,

                          var lastModifiedDateList: List[Timestamp],
                          var daysModifiedAheadOfTripList: List[Long],
                          var daysModifiedAheadOfTripMedian: Long,
                          var daysModifiedAheadOfTripDistinctCount: Int,
                          var cartEndDate: Timestamp,
                          var cartActiveDurationMinutesList: List[Long],
                          var cartActiveDurationMinutes: Long,

                          var dme: Boolean,
                          var destination: String,
                          var destinationList: List[String],
                          var flightExists: Boolean,
                          var groundTransferExists: Boolean,
                          var insuranceExists: Boolean,
                          var personalMagicExists: Boolean,
                          var rentalCarExists: Boolean,

                          var standalonePersonalMagicInd: Boolean,
                          var standalonePersonalMagicIndList: List[Boolean],
                          var standalonePersonalMagicNum: Int,
                          var standalonePersonalMagicNumList: List[Int],
                          var standalonePersonalMagicNumMedian: Int,
                          var standalonePersonalMagicNumDistinctCount: Int,

                          var packageTicketDescriptionList: List[String],
                          var packageTicketDescriptionDstcnt: Int,
                          var packageDineExistsList: List[Boolean],
                          var packageDineExists: Boolean,
                          var packageRoomExistsList: List[Boolean],
                          var packageRoomExists: Boolean,
                          var packageRoomOnlyList: List[Boolean],
                          var packageRoomOnly: Boolean,
                          var packageTicket: Boolean,
                          var isPackageList: List[Boolean],
                          var isPackage: Boolean,
                          var packageTicketNumDaysList: List[Double],
                          var packageTicketNumDays: Double,
                          var packageTicketNumDaysMedian: Double,
                          var packageTicketNumDaysDstcnt: Int,
                          var packageTicketParkHopperList: List[Boolean],
                          var packageTicketParkHopper: Boolean,
                          var packageTicketParkHopperPlusList: List[Boolean],
                          var packageTicketParkHopperPlus: Boolean,
                          var packageTicketAdultCntList: List[Int],
                          var packageTicketAdultCnt: Int,
                          var packageTicketAdultCntMax: Int,
                          var packageTicketAdultCntMedian: Int,
                          var packageTicketAdultCntDstcnt: Int,
                          var packageTicketChildCntList: List[Int],
                          var packageTicketChildCnt: Int,
                          var packageTicketChildCntMax: Int,
                          var packageTicketChildCntMedian: Int,
                          var packageTicketChildCntDstcnt: Int,

                          var packageTicketChildMinAgeList: List[Double],
                          var packageTicketChildMinAge: Double,
                          var packageTicketChildMinAgeMin: Double,

                          var packageTicketChildMaxAgeList: List[Double],
                          var packageTicketChildMaxAge: Double,
                          var packageTicketChildMaxAgeMax: Double,

                          var packageTicketWaterparkList: List[Boolean],
                          var packageTicketWaterpark: Boolean,
                          var numRoomsList: List[Int],
                          var numRooms: Int,
                          var numRoomsMin: Int,
                          var numRoomsMax: Int,
                          var numRoomsDistinctCount: Int,
                          var resortNameList: List[String],
                          var resortDstcnt: Int,
                          var roomAdultCntList: List[Int],
                          var roomAdultCnt: Int,
                          var roomAdultCntMedian: Int,
                          var roomAdultCntMax: Int,
                          var roomAdultCntDstcnt: Int,
                          var roomChildCnt: Int,
                          var roomChildCntList: List[Int],
                          var roomChildCntMax: Int,
                          var roomChildCntDstcnt: Int,
                          var roomChildCntMedian: Int,
                          var roomChildMinAge: Double,
                          var roomChildMinAgeList: List[Double],
                          var roomChildMinAgeDistinctCount: Int,
                          var roomChildMinAgeMedian:Double,
                          var roomChildMinAgeMin:Double,
                          var roomChildMaxAge: Double,
                          var roomChildMaxAgeList: List[Double],
                          var roomChildMaxAgeDistinctCount: Int,
                          var roomChildMaxAgeMedian:Double,
                          var roomChildMaxAgeMax: Double,

                          var roomNumDaysList: List[Int],
                          var roomNumDaysMin: Int,
                          var roomNumDaysMean: Double,
                          var roomNumDaysMax: Int,

                          var isStandalone: Boolean,
                          var isStandaloneList: List[Boolean],
                          var standaloneTicketDescriptionList:List[String],
                          var standaloneTicketDescriptionDstcnt: Int,
                          var standaloneTicketNumList: List[Int],
                          var standaloneTicketNumMedian: Int,
                          var standaloneTicketNumDistinctCount: Int,
                          var standaloneTicketNumDaysList: List[Int],
                          var standaloneTicketNumDaysMedian: Int,
                          var standaloneTicketNumDaysDistinctCount: Int,
                          var standaloneTicketParkHopper: Boolean,
                          var standaloneTicketParkHopperList: List[Boolean],
                          var standaloneTicketParkHopperPlus: Boolean,
                          var standaloneTicketParkHopperPlusList: List[Boolean],
                          var standaloneTicketAdultCountList: List[Int],
                          var standaloneTicketAdultCount: Int,
                          var standaloneTicketAdultCntMax: Int,
                          var standaloneTicketAdultCountMedian: Int,
                          var standaloneTicketAdultCountDistinctCount: Int,
                          var standaloneTicketChildCntList: List[Int],
                          var standaloneTicketChildCnt: Int,
                          var standaloneTicketChildCntMax: Int,
                          var standaloneTicketChildCntMedian: Int,
                          var standaloneTicketChildCntDstcnt: Int,

                          var adultCountMax: Int,
                          var adultCountMedian: Int,
                          var adultCountDistinctCount: Int,
                          var childCountMax: Int,
                          var childCountMedian: Int,
                          var childCountDistinctCount: Int,

                          var standaloneTicketChildMinAge: Double,
                          var standaloneTicketChildMinAgeList: List[Double],
                          var standaloneTicketChildMinAgeDistinctCount: Int,
                          var standaloneTicketChildMinAgeMin: Double,
                          var standaloneTicketChildMinAgeMedian: Double,

                          var standaloneTicketChildMaxAge: Double,
                          var standaloneTicketChildMaxAgeList: List[Double],
                          var standaloneTicketChildMaxAgeDistinctCount: Int,
                          var standaloneTicketChildMaxAgeMax: Double,
                          var standaloneTicketChildMaxAgeMedian: Double,

                          var standaloneTicketWaterParkList: List[Boolean],
                          var standaloneTicketWaterPark: Boolean

                        )
